### ISSUE TITLE
Primordial Leaves has a bad loot table. Ultimining them breaks block drops

### ISSUE THREAD

**Issue by Trent2087** [nvb-uy/Eldritch_End#12]
Primordial Leaves has a bad loot table. 
[20:14:14] [ForkJoinPool.commonPool-worker-5/WARN]: [RER] Failed to parse loot table 'eldritch_end:blocks/primordial_leaves': 
java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
	at jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64) ~[?:?]
	at jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70) ~[?:?]
	at jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266) ~[?:?]
	at java.util.Objects.checkIndex(Objects.java:361) ~[?:?]
	at java.util.ArrayList.get(ArrayList.java:427) ~[?:?]
	at com.google.gson.JsonArray.get(JsonArray.java:228) ~[gson-2.10.jar:?]
	at uk.me.desert_island.rer.rei_stuff.LootDisplay.munchLootCondition(LootDisplay.java:200) ~[rer-2.9.0.jar:?]
	
This causes an error in the console whenever they are mined.
https://hastebin.com/share/odehikoyes.ruby

If Ultimine is used on the leaves, it breaks block drops for all items until a restart. Obviously this part is just a symptom. Fixing the loot table will also prevent this issue.

**Comment by Trent2087** [comment]
Found the cause. After checking another mods leaves loot table, it appears you are missing the Explosion Chances in the json causing it to break. I added these chances to the loot table and that fixes the issue. 
![image](https://github.com/nvb-uy/Eldritch_End/assets/132113621/c4e79d07-e799-4a0c-bf07-eb54ba2ec17b)

https://github.com/nvb-uy/Eldritch_End/blob/91639d9b19937c64008bf1b216ef435f42f3a3ef/src/main/generated/data/eldritch_end/loot_tables/blocks/primordial_leaves.json#L49

**Comment by nvb-uy** [comment]
Interesting lol, will get it fixed by next update, thanks!

**Comment by nvb-uy** [comment]
Fixed indev 0.3.0
