### ISSUE TITLE
Server don't start

### ISSUE THREAD

**Issue by Mozork01** [nvb-uy/Eldritch_End#3]
Hey

Version 1.20.1
Fabric loader 0.14.24

I can play Minecraft with Eldritch end in solo game. but I can't play in server. Server don't start.
Server log :

java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'eldritch_end'!
	at net.fabricmc.loader.impl.FabricLoaderImpl.lambda$invokeEntrypoints$2(FabricLoaderImpl.java:387) ~[fabric-loader-0.14.24.jar:?]
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33) ~[fabric-loader-0.14.24.jar:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:385) ~[fabric-loader-0.14.24.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startServer(Hooks.java:63) ~[fabric-loader-0.14.24.jar:?]
	at net.minecraft.server.Main.main(Main.java:112) ~[server-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.14.24.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.14.24.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) ~[fabric-loader-0.14.24.jar:?]
	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) ~[fabric-loader-0.14.24.jar:?]
	at net.fabricmc.installer.ServerLauncher.main(ServerLauncher.java:69) ~[fabric-server-mc.1.20.1-loader.0.14.24-launcher.0.11.2.jar:0.11.2]
Caused by: java.lang.NoClassDefFoundError: net/minecraft/class_746
	at elocindev.eldritch_end.registry.ItemRegistry.<clinit>(ItemRegistry.java:52) ~[Eldritch_End-FABRIC-MC1.20.1-0.2.0.jar:?]
	at elocindev.eldritch_end.registry.BlockRegistry.registerFullBlock(BlockRegistry.java:370) ~[Eldritch_End-FABRIC-MC1.20.1-0.2.0.jar:?]
	at elocindev.eldritch_end.registry.BlockRegistry.register(BlockRegistry.java:282) ~[Eldritch_End-FABRIC-MC1.20.1-0.2.0.jar:?]
	at elocindev.eldritch_end.EldritchEnd.onInitialize(EldritchEnd.java:26) ~[Eldritch_End-FABRIC-MC1.20.1-0.2.0.jar:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:383) ~[fabric-loader-0.14.24.jar:?]
	... 7 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.class_746
	at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226) ~[fabric-loader-0.14.24.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.14.24.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at elocindev.eldritch_end.registry.ItemRegistry.<clinit>(ItemRegistry.java:52) ~[Eldritch_End-FABRIC-MC1.20.1-0.2.0.jar:?]
	at elocindev.eldritch_end.registry.BlockRegistry.registerFullBlock(BlockRegistry.java:370) ~[Eldritch_End-FABRIC-MC1.20.1-0.2.0.jar:?]
	at elocindev.eldritch_end.registry.BlockRegistry.register(BlockRegistry.java:282) ~[Eldritch_End-FABRIC-MC1.20.1-0.2.0.jar:?]
	at elocindev.eldritch_end.EldritchEnd.onInitialize(EldritchEnd.java:26) ~[Eldritch_End-FABRIC-MC1.20.1-0.2.0.jar:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:383) ~[fabric-loader-0.14.24.jar:?]
	... 7 more

**Comment by nvb-uy** [comment]
Can you send a full log?

**Comment by nvb-uy** [comment]
Fixed v0.2.12
