### ISSUE TITLE
Crash on Startup (Forge)

### ISSUE THREAD

**Issue by GlidingKnowItALL** [nvb-uy/Eldritch_End#8]
[14:50:09] [main/INFO] [necronomicon/]: Creating default config file for elocindev.eldritch_end.config.entries.CorruptionConfig.
[14:50:09] [main/INFO] [necronomicon/]: Creating default config file for elocindev.eldritch_end.config.entries.biomes.PrimordialAbyssConfig.
[14:50:09] [main/INFO] [necronomicon/]: Creating default config file for elocindev.eldritch_end.config.entries.biomes.HasturianWastesConfig.
[14:50:09] [main/INFO] [necronomicon/]: Creating default config file for elocindev.eldritch_end.config.entries.entities.AberrationConfig.
[14:50:09] [main/INFO] [necronomicon/]: Creating default config file for elocindev.eldritch_end.config.entries.entities.TentacleConfig.
[14:50:09] [main/INFO] [necronomicon/]: Creating default config file for elocindev.eldritch_end.config.entries.entities.DendlerConfig.
[14:50:09] [main/INFO] [necronomicon/]: Creating default config file for elocindev.eldritch_end.config.entries.entities.HasturConfig.
[14:50:09] [main/INFO] [eldritch_end/]: Eldritch End's Config Loaded!
[14:50:09] [main/ERROR] [ne.mi.fm.lo.RuntimeDistCleaner/DISTXFORM]: Attempted to load class net/minecraft/client/player/LocalPlayer for invalid dist DEDICATED_SERVER
[14:50:09] [main/ERROR] [minecraft/Main]: Failed to start the minecraft server
net.minecraftforge.fml.loading.EarlyLoadingException: Could not execute entrypoint stage 'main' due to errors, provided by 'eldritch_end'!
        at dev.su5ed.sinytra.connector.loader.ConnectorEarlyLoader.createLoadingException(ConnectorEarlyLoader.java:77) ~[Connector-1.0.0-beta.29+1.20.1.jar%23247!/:1.0.0-beta.29+1.20.1] {}
        at dev.su5ed.sinytra.connector.loader.ConnectorEarlyLoader.createGenericLoadingException(ConnectorEarlyLoader.java:73) ~[Connector-1.0.0-beta.29+1.20.1.jar%23247!/:1.0.0-beta.29+1.20.1] {}
        at dev.su5ed.sinytra.connector.mod.ConnectorLoader.load(ConnectorLoader.java:65) ~[Connector-1.0.0-beta.29+1.20.1-mod.jar%23252!/:1.0.0-beta.29+1.20.1] {re:mixin,re:classloading}
        at net.minecraft.server.Main.handler$cag000$connectormod$earlyInit(Main.java:1015) ~[server-1.20.1-20230612.114412-srg.jar%23399!/:?] {re:mixin,pl:connector_pre_launch:A,re:classloading,pl:mixin:A,pl:connector_pre_launch:A}
        at net.minecraft.server.Main.main(Main.java:125) ~[server-1.20.1-20230612.114412-srg.jar%23399!/:?] {re:mixin,pl:connector_pre_launch:A,re:classloading,pl:mixin:A,pl:connector_pre_launch:A}
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
        at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
        at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:111) ~[fmlloader-1.20.1-47.2.17.jar%2369!/:?] {}
        at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.serverService(CommonLaunchHandler.java:103) ~[fmlloader-1.20.1-47.2.17.jar%2369!/:?] {}
        at net.minecraftforge.fml.loading.targets.CommonServerLaunchHandler.lambda$makeService$0(CommonServerLaunchHandler.java:27) ~[fmlloader-1.20.1-47.2.17.jar%2369!/:?] {}
        at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) ~[modlauncher-10.0.9.jar%2355!/:?] {}
        at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) ~[modlauncher-10.0.9.jar%2355!/:?] {}
        at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) ~[modlauncher-10.0.9.jar%2355!/:?] {}
        at cpw.mods.modlauncher.Launcher.run(Launcher.java:108) ~[modlauncher-10.0.9.jar%2355!/:?] {}
        at cpw.mods.modlauncher.Launcher.main(Launcher.java:78) ~[modlauncher-10.0.9.jar%2355!/:?] {}
        at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) ~[modlauncher-10.0.9.jar%2355!/:?] {}
        at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) ~[modlauncher-10.0.9.jar%2355!/:?] {}
        at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) ~[bootstraplauncher-1.1.2.jar:?] {}
Caused by: java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'eldritch_end'!
        at net.fabricmc.loader.impl.FabricLoaderImpl.lambda$invokeEntrypoints$0(FabricLoaderImpl.java:131) ~[Connector-1.0.0-beta.29+1.20.1.jar%23247!/:1.0.0-beta.29+1.20.1] {}
        at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33) ~[Connector-1.0.0-beta.29+1.20.1.jar%23247!/:1.0.0-beta.29+1.20.1] {}
        at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:129) ~[Connector-1.0.0-beta.29+1.20.1.jar%23247!/:1.0.0-beta.29+1.20.1] {}
        at dev.su5ed.sinytra.connector.mod.ConnectorLoader.load(ConnectorLoader.java:53) ~[Connector-1.0.0-beta.29+1.20.1-mod.jar%23252!/:1.0.0-beta.29+1.20.1] {re:mixin,re:classloading}
        ... 17 more
Caused by: java.lang.ExceptionInInitializerError
        at elocindev.eldritch_end.registry.BlockRegistry.registerFullBlock(BlockRegistry.java:382) ~[Eldritch_End-FORGE-MC1.20.1-0.2.30_mapped_srg_1.20.1.jar%23737!/:?] {re:mixin,re:classloading}
        at elocindev.eldritch_end.registry.BlockRegistry.register(BlockRegistry.java:289) ~[Eldritch_End-FORGE-MC1.20.1-0.2.30_mapped_srg_1.20.1.jar%23737!/:?] {re:mixin,re:classloading}
        at elocindev.eldritch_end.EldritchEnd.onInitialize(EldritchEnd.java:27) ~[Eldritch_End-FORGE-MC1.20.1-0.2.30_mapped_srg_1.20.1.jar%23737!/:?] {re:classloading}
        at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:127) ~[Connector-1.0.0-beta.29+1.20.1.jar%23247!/:1.0.0-beta.29+1.20.1] {}
        at dev.su5ed.sinytra.connector.mod.ConnectorLoader.load(ConnectorLoader.java:53) ~[Connector-1.0.0-beta.29+1.20.1-mod.jar%23252!/:1.0.0-beta.29+1.20.1] {re:mixin,re:classloading}
        ... 17 more
Caused by: java.lang.RuntimeException: Attempted to load class net/minecraft/client/player/LocalPlayer for invalid dist DEDICATED_SERVER
        at net.minecraftforge.fml.loading.RuntimeDistCleaner.processClassWithFlags(RuntimeDistCleaner.java:57) ~[fmlloader-1.20.1-47.2.17.jar%2369!/:1.0] {}
        at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:88) ~[modlauncher-10.0.9.jar%2355!/:?] {}
        at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120) ~[modlauncher-10.0.9.jar%2355!/:?] {}
        at cpw.mods.modlauncher.TransformingClassLoader.maybeTransformClassBytes(TransformingClassLoader.java:50) ~[modlauncher-10.0.9.jar%2355!/:?] {}
        at cpw.mods.cl.ModuleClassLoader.readerToClass(ModuleClassLoader.java:113) ~[securejarhandler-2.1.10.jar:?] {}
        at cpw.mods.cl.ModuleClassLoader.lambda$findClass$15(ModuleClassLoader.java:219) ~[securejarhandler-2.1.10.jar:?] {}
        at cpw.mods.cl.ModuleClassLoader.loadFromModule(ModuleClassLoader.java:229) ~[securejarhandler-2.1.10.jar:?] {}
        at cpw.mods.cl.ModuleClassLoader.findClass(ModuleClassLoader.java:219) ~[securejarhandler-2.1.10.jar:?] {}
        at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:135) ~[securejarhandler-2.1.10.jar:?] {}
        at java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?] {}
        at elocindev.eldritch_end.registry.ItemRegistry.<clinit>(ItemRegistry.java:55) ~[Eldritch_End-FORGE-MC1.20.1-0.2.30_mapped_srg_1.20.1.jar%23737!/:?] {re:classloading}
        at elocindev.eldritch_end.registry.BlockRegistry.registerFullBlock(BlockRegistry.java:382) ~[Eldritch_End-FORGE-MC1.20.1-0.2.30_mapped_srg_1.20.1.jar%23737!/:?] {re:mixin,re:classloading}
        at elocindev.eldritch_end.registry.BlockRegistry.register(BlockRegistry.java:289) ~[Eldritch_End-FORGE-MC1.20.1-0.2.30_mapped_srg_1.20.1.jar%23737!/:?] {re:mixin,re:classloading}
        at elocindev.eldritch_end.EldritchEnd.onInitialize(EldritchEnd.java:27) ~[Eldritch_End-FORGE-MC1.20.1-0.2.30_mapped_srg_1.20.1.jar%23737!/:?] {re:classloading}
        at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:127) ~[Connector-1.0.0-beta.29+1.20.1.jar%23247!/:1.0.0-beta.29+1.20.1] {}
        at dev.su5ed.sinytra.connector.mod.ConnectorLoader.load(ConnectorLoader.java:53) ~[Connector-1.0.0-beta.29+1.20.1-mod.jar%23252!/:1.0.0-beta.29+1.20.1] {re:mixin,re:classloading}
        ... 17 more

------------------
Full Log:
[latest.log](https://github.com/nvb-uy/Eldritch_End/files/13648929/latest.log)

**Comment by nvb-uy** [comment]
Your forge version is likely too new, report this to the Connector issue tracker
